export const DEMO_ROOT_ID = '1:1';

export const DEMO_DOCUMENT = {
  id: '0:0',
  name: 'Demo Newsletter',
  type: 'DOCUMENT',
  children: [
    {
      id: '1:0',
      name: 'Page 1',
      type: 'CANVAS',
      children: [
        {
          id: DEMO_ROOT_ID,
          name: 'Email Newsletter',
          type: 'FRAME',
          absoluteBoundingBox: { x: 0, y: 0, width: 600, height: 760 },
          layoutMode: 'VERTICAL',
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
          itemSpacing: 0,
          fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 1, g: 1, b: 1 } }],
          children: [
            {
              id: '1:2',
              name: 'Hero',
              type: 'FRAME',
              absoluteBoundingBox: { x: 0, y: 0, width: 600, height: 240 },
              layoutMode: 'VERTICAL',
              paddingLeft: 40,
              paddingRight: 40,
              paddingTop: 60,
              paddingBottom: 60,
              itemSpacing: 16,
              primaryAxisAlignItems: 'CENTER',
              counterAxisAlignItems: 'CENTER',
              fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.1, g: 0.1, b: 0.2 } }],
              children: [
                {
                  id: '1:3',
                  name: 'Headline',
                  type: 'TEXT',
                  absoluteBoundingBox: { x: 80, y: 80, width: 440, height: 40 },
                  characters: 'Welcome to the Newsletter',
                  style: { fontSize: 32, fontFamily: 'Arial', fontWeight: 700 },
                  fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 1, g: 1, b: 1 } }],
                },
                {
                  id: '1:4',
                  name: 'Subhead',
                  type: 'TEXT',
                  absoluteBoundingBox: { x: 80, y: 140, width: 440, height: 20 },
                  characters: 'Your monthly update on what is new',
                  style: { fontSize: 16, fontFamily: 'Arial', fontWeight: 400 },
                  fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.8, g: 0.8, b: 0.85 } }],
                },
              ],
            },
            {
              id: '1:5',
              name: 'Body',
              type: 'FRAME',
              absoluteBoundingBox: { x: 0, y: 240, width: 600, height: 240 },
              layoutMode: 'VERTICAL',
              paddingLeft: 40,
              paddingRight: 40,
              paddingTop: 40,
              paddingBottom: 40,
              itemSpacing: 16,
              fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 1, g: 1, b: 1 } }],
              children: [
                {
                  id: '1:6',
                  name: 'Body Headline',
                  type: 'TEXT',
                  absoluteBoundingBox: { x: 40, y: 280, width: 520, height: 28 },
                  characters: 'What is new this month',
                  style: { fontSize: 22, fontFamily: 'Arial', fontWeight: 700 },
                  fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.1, g: 0.1, b: 0.2 } }],
                },
                {
                  id: '1:7',
                  name: 'Body Text',
                  type: 'TEXT',
                  absoluteBoundingBox: { x: 40, y: 320, width: 520, height: 80 },
                  characters: 'We have been working on improvements based on your feedback. This month we shipped faster exports, cleaner output, and better preview accuracy across Gmail, Apple Mail, and Outlook.',
                  style: { fontSize: 16, fontFamily: 'Arial', fontWeight: 400 },
                  fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.25, g: 0.25, b: 0.3 } }],
                },
              ],
            },
            {
              id: '1:8',
              name: 'CTA Section',
              type: 'FRAME',
              absoluteBoundingBox: { x: 0, y: 480, width: 600, height: 120 },
              layoutMode: 'VERTICAL',
              paddingLeft: 40,
              paddingRight: 40,
              paddingTop: 24,
              paddingBottom: 40,
              itemSpacing: 16,
              primaryAxisAlignItems: 'CENTER',
              counterAxisAlignItems: 'CENTER',
              fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.97, g: 0.97, b: 1 } }],
              children: [
                {
                  id: '1:9',
                  name: 'Button',
                  type: 'FRAME',
                  absoluteBoundingBox: { x: 240, y: 504, width: 120, height: 48 },
                  layoutMode: 'HORIZONTAL',
                  paddingLeft: 24,
                  paddingRight: 24,
                  paddingTop: 12,
                  paddingBottom: 12,
                  itemSpacing: 0,
                  primaryAxisAlignItems: 'CENTER',
                  counterAxisAlignItems: 'CENTER',
                  fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.39, g: 0.4, b: 0.94 } }],
                  children: [
                    {
                      id: '1:10',
                      name: 'Button Label',
                      type: 'TEXT',
                      absoluteBoundingBox: { x: 264, y: 516, width: 72, height: 24 },
                      characters: 'Read more',
                      style: { fontSize: 16, fontFamily: 'Arial', fontWeight: 600 },
                      fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 1, g: 1, b: 1 } }],
                    },
                  ],
                },
              ],
            },
            {
              id: '1:11',
              name: 'Footer',
              type: 'FRAME',
              absoluteBoundingBox: { x: 0, y: 600, width: 600, height: 80 },
              layoutMode: 'VERTICAL',
              paddingLeft: 40,
              paddingRight: 40,
              paddingTop: 24,
              paddingBottom: 24,
              itemSpacing: 8,
              primaryAxisAlignItems: 'CENTER',
              counterAxisAlignItems: 'CENTER',
              fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.96, g: 0.96, b: 0.97 } }],
              children: [
                {
                  id: '1:12',
                  name: 'Footer Text',
                  type: 'TEXT',
                  absoluteBoundingBox: { x: 100, y: 624, width: 400, height: 16 },
                  characters: 'You are receiving this because you subscribed at example.com',
                  style: { fontSize: 12, fontFamily: 'Arial', fontWeight: 400 },
                  fills: [{ type: 'SOLID', visible: true, opacity: 1, color: { r: 0.5, g: 0.5, b: 0.55 } }],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
